TIME_ZONE: 'Rome'
LOCALE: 'it'
SECRET_TOKEN: 'SecretToken1'
MAIL_SENDER: 'noreply@example.com'
DEVISE_SECRET: 'SecretToken2'
DEVISE_PEPPER: 'SecretToken3'
FORCE_SSL: 'false'
SITE_NAME: 'Herudio'
HOST: 'localhost:5000'
SMTP_ADDRESS: 'mail.example.com'
SMTP_PORT: '587'
SMTP_DOMAIN: 'example.com'
SMTP_USER: 'noreply@example.com'
SMTP_PASS: 'MyPassword'
SMTP_AUTH: 'plain'
SMTP_STARTTLS: 'true'
