TIME_ZONE: 'Rome'
LOCALE: 'it'
SECRET_TOKEN: 'SecretToken1'
SECRET_KEY_BASE: 'SecretToken4'
MAIL_SENDER: 'noreply@example.com'
DEVISE_SECRET: 'SecretToken2'
DEVISE_PEPPER: 'SecretToken3'
FORCE_SSL: 'false'
SITE_NAME: 'Herudio'
HOST: 'localhost:5000'
SMTP_ADDRESS: 'mail.example.com'
SMTP_PORT: '587'
SMTP_DOMAIN: 'example.com'
SMTP_USER: 'noreply@example.com'
SMTP_PASS: 'MyPassword'
SMTP_AUTH: 'plain'
SMTP_STARTTLS: 'true'
SUBSCRIPTIONS_OPEN_AT: '2014-01-01 00:00'
SUBSCRIPTIONS_CLOSE_AT: '2014-02-01 00:00'
BEA_URL: 'https://www.facebook.com/beatrice.latini.7'
RAFFO_URL: 'https://www.facebook.com/raffaele.biondo1'
ROCCIA_URL: 'https://www.facebook.com/giovanni.roccetti'
TITTO_URL: 'https://www.facebook.com/tittobello'
