TIME_ZONE: 'Rome'
LOCALE: 'it'
SECRET_TOKEN: 'SecretToken1'
SECRET_KEY_BASE: 'SecretToken4'
MAIL_SENDER: 'noreply@example.com'
DEVISE_SECRET: 'SecretToken2'
DEVISE_PEPPER: 'SecretToken3'
FORCE_SSL: 'false'
SITE_NAME: 'Herudio'
HOST: 'localhost:5000'
SMTP_ADDRESS: 'mail.example.com'
SMTP_PORT: '587'
SMTP_DOMAIN: 'example.com'
SMTP_USER: 'noreply@example.com'
SMTP_PASS: 'MyPassword'
SMTP_AUTH: 'plain'
SMTP_STARTTLS: 'true'
SUBSCRIPTIONS_OPEN_AT: '2014-01-01 00:00'
SUBSCRIPTIONS_CLOSE_AT: '2014-02-01 00:00'
TEAM_IMAGES: 'http://www.example.com/img1.jpg|http://www.example.com/img2.jpg'
TEAM_URLS: 'http://www.example.com/person1|http://www.example.com/person2'
CONTACT_EMAIL: 'herudio@karmapen.com'
TEAM_NAMES: 'John Doe'
ORG_IMAGE: 'http://www.example.com/img1.jpg'
ORG_URL: 'http://www.example.com'
