development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: herudio_development
  pool:     5
  username: herudio
  password: herudio
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: herudio_test
  pool:     5
  username: herudio
  password: herudio
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: herudio_production
  pool:     5
  username: herudio
  password: herudio
  template: template0
