# pg_restore --verbose --clean --no-acl --no-owner -h localhost -d herudio_development db/latest.dump

development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: herudio_development
  pool:     5
  username: postgres
  password: postgres
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: herudio_test
  pool:     5
  username: postgres
  password: postgres
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: herudio_production
  pool:     5
  username: postgres
  password: postgres
  template: template0
